[package]
name = "wpush-git"
version = "0.1.4"
edition = "2021"
description = "A CLI tool to clone Git repositories on Windows and push them into WSL filesystem seamlessly."
license = "MIT OR Apache-2.0"
repository = "https://github.com/0xA672/wpush"
readme = "README.md"
keywords = ["wsl", "git", "windows", "cli", "productivity"]
categories = ["command-line-utilities", "development-tools"]
authors = ["0xA672 <Cero0xA672@outlook.com>"]

[dependencies]
clap = { version = "4.5", features = ["derive", "env"] }
clap_complete = "4.5"
tempfile = "3.10"
anyhow = "1.0"
git2 = "0.20.4"
colored = "3.1.1"
indoc = "2.0.7"
indicatif = "0.17"
console = "0.15"

[[bin]]
name = "wpush"
path = "src/wpush.rs"

[profile.release-max]
inherits = "release"
lto = "fat"
codegen-units = 1
opt-level = 3
panic = "abort"
incremental = false
strip = "symbols"
